// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: consensus.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftNode_Propose_FullMethodName = "/consensus.RaftNode/Propose"
	RaftNode_Read_FullMethodName    = "/consensus.RaftNode/Read"
)

// RaftNodeClient is the client API for RaftNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftNodeClient interface {
	Propose(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ProposeResponse, error)
	// Phase 4 — a linearizable read. Served by the LEADER: it runs Barrier() +
	// VerifyLeader() and only then reads its own local state machine, which is
	// what makes the answer linearizable rather than merely recent. A follower
	// forwards exactly once (see ReadRequest.forwarded).
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type raftNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftNodeClient(cc grpc.ClientConnInterface) RaftNodeClient {
	return &raftNodeClient{cc}
}

func (c *raftNodeClient) Propose(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, RaftNode_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNodeClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, RaftNode_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftNodeServer is the server API for RaftNode service.
// All implementations must embed UnimplementedRaftNodeServer
// for forward compatibility.
type RaftNodeServer interface {
	Propose(context.Context, *Command) (*ProposeResponse, error)
	// Phase 4 — a linearizable read. Served by the LEADER: it runs Barrier() +
	// VerifyLeader() and only then reads its own local state machine, which is
	// what makes the answer linearizable rather than merely recent. A follower
	// forwards exactly once (see ReadRequest.forwarded).
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	mustEmbedUnimplementedRaftNodeServer()
}

// UnimplementedRaftNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftNodeServer struct{}

func (UnimplementedRaftNodeServer) Propose(context.Context, *Command) (*ProposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedRaftNodeServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedRaftNodeServer) mustEmbedUnimplementedRaftNodeServer() {}
func (UnimplementedRaftNodeServer) testEmbeddedByValue()                  {}

// UnsafeRaftNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftNodeServer will
// result in compilation errors.
type UnsafeRaftNodeServer interface {
	mustEmbedUnimplementedRaftNodeServer()
}

func RegisterRaftNodeServer(s grpc.ServiceRegistrar, srv RaftNodeServer) {
	// If the following call panics, it indicates UnimplementedRaftNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftNode_ServiceDesc, srv)
}

func _RaftNode_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNodeServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftNode_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNodeServer).Propose(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftNode_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNodeServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftNode_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNodeServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftNode_ServiceDesc is the grpc.ServiceDesc for RaftNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.RaftNode",
	HandlerType: (*RaftNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _RaftNode_Propose_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _RaftNode_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensus.proto",
}

const (
	StateMachine_Apply_FullMethodName           = "/consensus.StateMachine/Apply"
	StateMachine_Get_FullMethodName             = "/consensus.StateMachine/Get"
	StateMachine_GetSnapshot_FullMethodName     = "/consensus.StateMachine/GetSnapshot"
	StateMachine_RestoreSnapshot_FullMethodName = "/consensus.StateMachine/RestoreSnapshot"
)

// StateMachineClient is the client API for StateMachine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateMachineClient interface {
	Apply(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ApplyResponse, error)
	// Phase 4 — a plain local read of the C++ store, with no consensus involved.
	// This is deliberately NOT a linearizable read on its own: it is the second
	// half of one, called by the sidecar only after that sidecar has verified it
	// is still the leader. Calling it directly gives you exactly what
	// GET ?consistency=local gives you.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Phase 3 — raft snapshot lifecycle. The C++ engine owns the state, so it
	// serves both directions: Go asks for a snapshot to hand to raft, and hands
	// a snapshot back when raft restores one.
	//
	// Chunk payloads are the Phase 2 base-file encoding ("KVB1" + length-prefixed
	// records) — one format for disk and wire, so a snapshot is byte-identical to
	// what kv.db would contain.
	GetSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error)
	RestoreSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SnapshotChunk, RestoreResponse], error)
}

type stateMachineClient struct {
	cc grpc.ClientConnInterface
}

func NewStateMachineClient(cc grpc.ClientConnInterface) StateMachineClient {
	return &stateMachineClient{cc}
}

func (c *stateMachineClient) Apply(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, StateMachine_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateMachineClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, StateMachine_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateMachineClient) GetSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateMachine_ServiceDesc.Streams[0], StateMachine_GetSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, SnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateMachine_GetSnapshotClient = grpc.ServerStreamingClient[SnapshotChunk]

func (c *stateMachineClient) RestoreSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SnapshotChunk, RestoreResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateMachine_ServiceDesc.Streams[1], StateMachine_RestoreSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotChunk, RestoreResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateMachine_RestoreSnapshotClient = grpc.ClientStreamingClient[SnapshotChunk, RestoreResponse]

// StateMachineServer is the server API for StateMachine service.
// All implementations must embed UnimplementedStateMachineServer
// for forward compatibility.
type StateMachineServer interface {
	Apply(context.Context, *Command) (*ApplyResponse, error)
	// Phase 4 — a plain local read of the C++ store, with no consensus involved.
	// This is deliberately NOT a linearizable read on its own: it is the second
	// half of one, called by the sidecar only after that sidecar has verified it
	// is still the leader. Calling it directly gives you exactly what
	// GET ?consistency=local gives you.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Phase 3 — raft snapshot lifecycle. The C++ engine owns the state, so it
	// serves both directions: Go asks for a snapshot to hand to raft, and hands
	// a snapshot back when raft restores one.
	//
	// Chunk payloads are the Phase 2 base-file encoding ("KVB1" + length-prefixed
	// records) — one format for disk and wire, so a snapshot is byte-identical to
	// what kv.db would contain.
	GetSnapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error
	RestoreSnapshot(grpc.ClientStreamingServer[SnapshotChunk, RestoreResponse]) error
	mustEmbedUnimplementedStateMachineServer()
}

// UnimplementedStateMachineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateMachineServer struct{}

func (UnimplementedStateMachineServer) Apply(context.Context, *Command) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedStateMachineServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStateMachineServer) GetSnapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error {
	return status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedStateMachineServer) RestoreSnapshot(grpc.ClientStreamingServer[SnapshotChunk, RestoreResponse]) error {
	return status.Error(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedStateMachineServer) mustEmbedUnimplementedStateMachineServer() {}
func (UnimplementedStateMachineServer) testEmbeddedByValue()                      {}

// UnsafeStateMachineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateMachineServer will
// result in compilation errors.
type UnsafeStateMachineServer interface {
	mustEmbedUnimplementedStateMachineServer()
}

func RegisterStateMachineServer(s grpc.ServiceRegistrar, srv StateMachineServer) {
	// If the following call panics, it indicates UnimplementedStateMachineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateMachine_ServiceDesc, srv)
}

func _StateMachine_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateMachineServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateMachine_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateMachineServer).Apply(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateMachine_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateMachineServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateMachine_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateMachineServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateMachine_GetSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateMachineServer).GetSnapshot(m, &grpc.GenericServerStream[SnapshotRequest, SnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateMachine_GetSnapshotServer = grpc.ServerStreamingServer[SnapshotChunk]

func _StateMachine_RestoreSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateMachineServer).RestoreSnapshot(&grpc.GenericServerStream[SnapshotChunk, RestoreResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateMachine_RestoreSnapshotServer = grpc.ClientStreamingServer[SnapshotChunk, RestoreResponse]

// StateMachine_ServiceDesc is the grpc.ServiceDesc for StateMachine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateMachine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.StateMachine",
	HandlerType: (*StateMachineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _StateMachine_Apply_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StateMachine_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSnapshot",
			Handler:       _StateMachine_GetSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RestoreSnapshot",
			Handler:       _StateMachine_RestoreSnapshot_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "consensus.proto",
}
