// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: consensus.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftNode_Propose_FullMethodName = "/consensus.RaftNode/Propose"
)

// RaftNodeClient is the client API for RaftNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftNodeClient interface {
	Propose(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ProposeResponse, error)
}

type raftNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftNodeClient(cc grpc.ClientConnInterface) RaftNodeClient {
	return &raftNodeClient{cc}
}

func (c *raftNodeClient) Propose(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, RaftNode_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftNodeServer is the server API for RaftNode service.
// All implementations must embed UnimplementedRaftNodeServer
// for forward compatibility.
type RaftNodeServer interface {
	Propose(context.Context, *Command) (*ProposeResponse, error)
	mustEmbedUnimplementedRaftNodeServer()
}

// UnimplementedRaftNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftNodeServer struct{}

func (UnimplementedRaftNodeServer) Propose(context.Context, *Command) (*ProposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedRaftNodeServer) mustEmbedUnimplementedRaftNodeServer() {}
func (UnimplementedRaftNodeServer) testEmbeddedByValue()                  {}

// UnsafeRaftNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftNodeServer will
// result in compilation errors.
type UnsafeRaftNodeServer interface {
	mustEmbedUnimplementedRaftNodeServer()
}

func RegisterRaftNodeServer(s grpc.ServiceRegistrar, srv RaftNodeServer) {
	// If the following call panics, it indicates UnimplementedRaftNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftNode_ServiceDesc, srv)
}

func _RaftNode_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNodeServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftNode_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNodeServer).Propose(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftNode_ServiceDesc is the grpc.ServiceDesc for RaftNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.RaftNode",
	HandlerType: (*RaftNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _RaftNode_Propose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensus.proto",
}

const (
	StateMachine_Apply_FullMethodName = "/consensus.StateMachine/Apply"
)

// StateMachineClient is the client API for StateMachine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateMachineClient interface {
	Apply(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ApplyResponse, error)
}

type stateMachineClient struct {
	cc grpc.ClientConnInterface
}

func NewStateMachineClient(cc grpc.ClientConnInterface) StateMachineClient {
	return &stateMachineClient{cc}
}

func (c *stateMachineClient) Apply(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, StateMachine_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateMachineServer is the server API for StateMachine service.
// All implementations must embed UnimplementedStateMachineServer
// for forward compatibility.
type StateMachineServer interface {
	Apply(context.Context, *Command) (*ApplyResponse, error)
	mustEmbedUnimplementedStateMachineServer()
}

// UnimplementedStateMachineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateMachineServer struct{}

func (UnimplementedStateMachineServer) Apply(context.Context, *Command) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedStateMachineServer) mustEmbedUnimplementedStateMachineServer() {}
func (UnimplementedStateMachineServer) testEmbeddedByValue()                      {}

// UnsafeStateMachineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateMachineServer will
// result in compilation errors.
type UnsafeStateMachineServer interface {
	mustEmbedUnimplementedStateMachineServer()
}

func RegisterStateMachineServer(s grpc.ServiceRegistrar, srv StateMachineServer) {
	// If the following call panics, it indicates UnimplementedStateMachineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateMachine_ServiceDesc, srv)
}

func _StateMachine_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateMachineServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateMachine_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateMachineServer).Apply(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

// StateMachine_ServiceDesc is the grpc.ServiceDesc for StateMachine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateMachine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.StateMachine",
	HandlerType: (*StateMachineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _StateMachine_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensus.proto",
}
