// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: consensus.proto

#include "consensus.pb.h"
#include "consensus.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace consensus {

static const char* RaftNode_method_names[] = {
  "/consensus.RaftNode/Propose",
};

std::unique_ptr< RaftNode::Stub> RaftNode::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RaftNode::Stub> stub(new RaftNode::Stub(channel, options));
  return stub;
}

RaftNode::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Propose_(RaftNode_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RaftNode::Stub::Propose(::grpc::ClientContext* context, const ::consensus::Command& request, ::consensus::ProposeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::consensus::Command, ::consensus::ProposeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Propose_, context, request, response);
}

void RaftNode::Stub::async::Propose(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::consensus::Command, ::consensus::ProposeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Propose_, context, request, response, std::move(f));
}

void RaftNode::Stub::async::Propose(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Propose_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::consensus::ProposeResponse>* RaftNode::Stub::PrepareAsyncProposeRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::consensus::ProposeResponse, ::consensus::Command, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Propose_, context, request);
}

::grpc::ClientAsyncResponseReader< ::consensus::ProposeResponse>* RaftNode::Stub::AsyncProposeRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProposeRaw(context, request, cq);
  result->StartCall();
  return result;
}

RaftNode::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftNode_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftNode::Service, ::consensus::Command, ::consensus::ProposeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftNode::Service* service,
             ::grpc::ServerContext* ctx,
             const ::consensus::Command* req,
             ::consensus::ProposeResponse* resp) {
               return service->Propose(ctx, req, resp);
             }, this)));
}

RaftNode::Service::~Service() {
}

::grpc::Status RaftNode::Service::Propose(::grpc::ServerContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* StateMachine_method_names[] = {
  "/consensus.StateMachine/Apply",
};

std::unique_ptr< StateMachine::Stub> StateMachine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StateMachine::Stub> stub(new StateMachine::Stub(channel, options));
  return stub;
}

StateMachine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Apply_(StateMachine_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StateMachine::Stub::Apply(::grpc::ClientContext* context, const ::consensus::Command& request, ::consensus::ApplyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::consensus::Command, ::consensus::ApplyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Apply_, context, request, response);
}

void StateMachine::Stub::async::Apply(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::consensus::Command, ::consensus::ApplyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Apply_, context, request, response, std::move(f));
}

void StateMachine::Stub::async::Apply(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Apply_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::consensus::ApplyResponse>* StateMachine::Stub::PrepareAsyncApplyRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::consensus::ApplyResponse, ::consensus::Command, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Apply_, context, request);
}

::grpc::ClientAsyncResponseReader< ::consensus::ApplyResponse>* StateMachine::Stub::AsyncApplyRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncApplyRaw(context, request, cq);
  result->StartCall();
  return result;
}

StateMachine::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StateMachine_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StateMachine::Service, ::consensus::Command, ::consensus::ApplyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StateMachine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::consensus::Command* req,
             ::consensus::ApplyResponse* resp) {
               return service->Apply(ctx, req, resp);
             }, this)));
}

StateMachine::Service::~Service() {
}

::grpc::Status StateMachine::Service::Apply(::grpc::ServerContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace consensus

