// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: consensus.proto
#ifndef GRPC_consensus_2eproto__INCLUDED
#define GRPC_consensus_2eproto__INCLUDED

#include "consensus.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace consensus {

class RaftNode final {
 public:
  static constexpr char const* service_full_name() {
    return "consensus.RaftNode";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Propose(::grpc::ClientContext* context, const ::consensus::Command& request, ::consensus::ProposeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ProposeResponse>> AsyncPropose(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ProposeResponse>>(AsyncProposeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ProposeResponse>> PrepareAsyncPropose(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ProposeResponse>>(PrepareAsyncProposeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Propose(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Propose(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ProposeResponse>* AsyncProposeRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ProposeResponse>* PrepareAsyncProposeRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Propose(::grpc::ClientContext* context, const ::consensus::Command& request, ::consensus::ProposeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::consensus::ProposeResponse>> AsyncPropose(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::consensus::ProposeResponse>>(AsyncProposeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::consensus::ProposeResponse>> PrepareAsyncPropose(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::consensus::ProposeResponse>>(PrepareAsyncProposeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Propose(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response, std::function<void(::grpc::Status)>) override;
      void Propose(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::consensus::ProposeResponse>* AsyncProposeRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::consensus::ProposeResponse>* PrepareAsyncProposeRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Propose_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Propose(::grpc::ServerContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Propose() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ProposeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPropose(::grpc::ServerContext* context, ::consensus::Command* request, ::grpc::ServerAsyncResponseWriter< ::consensus::ProposeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Propose<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Propose() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::consensus::Command, ::consensus::ProposeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::consensus::Command* request, ::consensus::ProposeResponse* response) { return this->Propose(context, request, response); }));}
    void SetMessageAllocatorFor_Propose(
        ::grpc::MessageAllocator< ::consensus::Command, ::consensus::ProposeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::consensus::Command, ::consensus::ProposeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ProposeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Propose(
      ::grpc::CallbackServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ProposeResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Propose<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Propose() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ProposeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Propose() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ProposeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPropose(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Propose() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Propose(context, request, response); }));
    }
    ~WithRawCallbackMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ProposeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Propose(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Propose() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::consensus::Command, ::consensus::ProposeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::consensus::Command, ::consensus::ProposeResponse>* streamer) {
                       return this->StreamedPropose(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ProposeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPropose(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::consensus::Command,::consensus::ProposeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Propose<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Propose<Service > StreamedService;
};

class StateMachine final {
 public:
  static constexpr char const* service_full_name() {
    return "consensus.StateMachine";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Apply(::grpc::ClientContext* context, const ::consensus::Command& request, ::consensus::ApplyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ApplyResponse>> AsyncApply(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ApplyResponse>>(AsyncApplyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ApplyResponse>> PrepareAsyncApply(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ApplyResponse>>(PrepareAsyncApplyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Apply(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Apply(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ApplyResponse>* AsyncApplyRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::consensus::ApplyResponse>* PrepareAsyncApplyRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Apply(::grpc::ClientContext* context, const ::consensus::Command& request, ::consensus::ApplyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::consensus::ApplyResponse>> AsyncApply(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::consensus::ApplyResponse>>(AsyncApplyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::consensus::ApplyResponse>> PrepareAsyncApply(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::consensus::ApplyResponse>>(PrepareAsyncApplyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Apply(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response, std::function<void(::grpc::Status)>) override;
      void Apply(::grpc::ClientContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::consensus::ApplyResponse>* AsyncApplyRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::consensus::ApplyResponse>* PrepareAsyncApplyRaw(::grpc::ClientContext* context, const ::consensus::Command& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Apply_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Apply(::grpc::ServerContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Apply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Apply() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Apply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Apply(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ApplyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestApply(::grpc::ServerContext* context, ::consensus::Command* request, ::grpc::ServerAsyncResponseWriter< ::consensus::ApplyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Apply<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Apply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Apply() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::consensus::Command, ::consensus::ApplyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::consensus::Command* request, ::consensus::ApplyResponse* response) { return this->Apply(context, request, response); }));}
    void SetMessageAllocatorFor_Apply(
        ::grpc::MessageAllocator< ::consensus::Command, ::consensus::ApplyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::consensus::Command, ::consensus::ApplyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Apply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Apply(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ApplyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Apply(
      ::grpc::CallbackServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ApplyResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Apply<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Apply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Apply() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Apply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Apply(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ApplyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Apply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Apply() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Apply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Apply(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ApplyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestApply(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Apply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Apply() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Apply(context, request, response); }));
    }
    ~WithRawCallbackMethod_Apply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Apply(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ApplyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Apply(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Apply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Apply() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::consensus::Command, ::consensus::ApplyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::consensus::Command, ::consensus::ApplyResponse>* streamer) {
                       return this->StreamedApply(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Apply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Apply(::grpc::ServerContext* /*context*/, const ::consensus::Command* /*request*/, ::consensus::ApplyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedApply(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::consensus::Command,::consensus::ApplyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Apply<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Apply<Service > StreamedService;
};

}  // namespace consensus


#endif  // GRPC_consensus_2eproto__INCLUDED
